#!/usr/bin/env bash

if [[ "$#" -lt 4 ]]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

file_path=$1
ip=$2
username=$3
ssh_key=$4

# Disable strict host key checking
ssh_options="-o StrictHostKeyChecking=no"

# Transfer the file to the user home directory
scp -i "$ssh_key" $ssh_options "$file_path" "$username@$ip":~
