#!/usr/bin/env bash
# Installs nginx server on an ubuntu linux distro.
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
