#!/usr/bin/env bash
# confiures a new ubuntu server by installing nginx
sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx start
