#!/usr/bin/env bash
# A script that Configures Nginx to redirect requests

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx to redirect requests
sudo sed -i '/server_name _;/a \\n    location /redirect_me {\n        return 301 http://example.com/newpage;\n    }' /etc/nginx/sites-available/default

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo service nginx reload
