#!/usr/bin/env bash
# A bash script that installs nginx on an ubuntu machine.
# The scripts also configures the default webpage served to be "Hello World!"
# When the following url requested matches /redirect_me, it redirects to a youtube channel.


sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "48i\\\tif (\$request_filename ~ redirect_me){\n\t\t\
rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}" /etc/nginx/sites-available/default

service nginx restart
