#!/usr/bin/env bash
# This script configures an Nginx HTTP response header to containa custom header
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i '/http {/a \
	add_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo service nginx restart
