#!/usr/bin/env bash
# same as task 0 but -f added to ln to forcefully remove the file if it exists
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
