#!/usr/bin/env bash
# A script that displays Best School 10 times and hi after the 9th using while and if

i=1

while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done