#!/usr/bin/env bash
# Creates and runs whoami command as specified user

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <username>"
  exit 1
fi

if id "$1" &>/dev/null; then
  sudo -u "$1" whoami
else
  echo "User $1 does not exist."
fi
